[General]
default_locale = "en-US"

[Database]
; Database connection string. See
; https://www.doctrine-project.org/projects/doctrine-dbal/en/4.4/reference/configuration.html#connecting-using-a-url
; for more information. `charset=utf8mb4` is included automatically unless something else is defined in the dsn.
;dsn = "mysql://user:pass@localhost/mlinvoice"
; Table name prefix. Default is "mlinvoice_"
;table_prefix = "mlinvoice_"

; Active languages/locales
[Locales]
en-US = "English (US)"
en-FI = "English (FI)"
fi-FI = "Finnish"
sv-FI = "Swedish"

[Logging]
; Logging level. ERROR level is generally suitable for production, while DEBUG
; works for development or troubleshooting.
; See https://github.com/Seldaek/monolog/blob/main/doc/01-usage.md#log-levels for more information.
level = ERROR
; Log error details?
log_error_details = true

; Session settings. See https://www.php.net/manual/en/session.configuration.php for more information.
[Session]
; Session lifetime in seconds. Note that if keepalive, if enabled in settings, will keep the session active longer when
; MLInvoice is open.
lifetime = 600
; Session cookie name
name = "MLINVOICESESSION"
; Set to true to only send the cookie over https. Default is false.
cookie_secure = false
; Set to true to testrict cookie path to any subdirectory MLInvoice is installed in. Default is true.
restrict_path = true
